# Generated by Django 5.0.3 on 2024-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
