# Generated by Django 5.0.3 on 2024-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0005_comment_delete_comentario_remove_camera_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="num_comements",
            field=models.IntegerField(default=0),
        ),
    ]
