# Generated by Django 5.0.3 on 2024-04-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0007_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teveo_app.datasource",
            ),
        ),
    ]
