# Generated by Django 5.0.3 on 2024-04-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0008_camera_data_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="num_comements",
            new_name="num_comments",
        ),
    ]
