# Generated by Django 5.0.3 on 2024-04-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0010_camera_img_camera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="img_camera",
        ),
    ]
