# Generated by Django 5.0.3 on 2024-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0011_remove_camera_img_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="img_camera",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
