# Generated by Django 5.0.3 on 2024-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0012_camera_img_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
