# Generated by Django 5.0.3 on 2024-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0014_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="num_likes",
            field=models.IntegerField(default=0),
        ),
    ]
