# Generated by Django 5.0.3 on 2024-06-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0015_camera_num_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="data_source",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
