# Generated by Django 5.0.3 on 2024-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
