# Generated by Django 5.0.3 on 2024-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0002_alter_camera_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
