# Generated by Django 5.0.3 on 2024-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0003_camera_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(default="", max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="camera",
            name="latitude",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="longitude",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="message",
            field=models.CharField(default="", max_length=200),
        ),
    ]
