# Generated by Django 5.0.3 on 2024-04-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0004_comentario_camera_latitude_camera_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("text", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="message",
        ),
        migrations.AddField(
            model_name="comment",
            name="id_camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teveo_app.camera"
            ),
        ),
    ]
