# Generated by Django 5.0.3 on 2024-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teveo_app", "0009_rename_num_comements_camera_num_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="img_camera",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
